server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cynosdbmysql-ilu90rxg/springboot_demo
    username: root
    password: #Jj130432432
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mysql
#    username: root
#    password: 123569

  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
